---
title: "TugasAkhir"
author: "Khalil"
date: "1/16/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
  library(shiny)
  library(here)
  library(vroom)
  library(ggplot2)
  library(dplyr)
  library(plotly)
  library(semantic.dashboard)
  library(DT)
  library(tidytext)
  library(skimr)
  library(topicmodels)
  library(tm)
  library(syuzhet)
  
  restaurant_data <- vroom(here("Tugas Akhir", "dataset", "review.csv"))
  as_tibble(restaurant_data)

```

```{r}
  restaurant_data = restaurant_data %>% mutate(Respone = ifelse(Liked == 1,"Positive","Negative"))
```
Word Cloud
```{r}
  #Create a vector containing only the text
  text <- restaurant_data$Review
  # Create a corpus  
  docs <- Corpus(VectorSource(text))

  docs <- docs %>%
  tm_map(removeNumbers) %>%
  tm_map(removePunctuation) %>%
  tm_map(stripWhitespace)
  docs <- tm_map(docs, content_transformer(tolower))
  docs <- tm_map(docs, removeWords, stopwords("english"))
  
  dtm <- TermDocumentMatrix(docs) 
  matrix <- as.matrix(dtm) 
  words <- sort(rowSums(matrix),decreasing=TRUE) 
  df <- data.frame(word = names(words),freq=words)
  
  set.seed(1234) # for reproducibility 
  wordcloud(words = df$word, freq = df$freq, min.freq = 1, 
            scale=c(3.5,0.25),
            max.words=200, random.order=FALSE, rot.per=0.35,    
            colors=brewer.pal(8, "Dark2"))
```


#codingan biasa
```{r}
  restaurant_data %>% 
  unnest_tokens(word, Review) %>%
  ungroup() %>%
  anti_join(stop_words) -> restaurant_dataPerKata 

  restaurant_dataPerKata %>% 
    count(Nickname, word, sort = TRUE)
  
  restaurant_data_ifidf <- restaurant_dataPerKata %>% 
    count(Nickname, word, sort = TRUE) %>% 
    bind_tf_idf(word, Nickname, n)
  
  #Kata Penting pada tiap-tiap orang
  restaurant_data_ifidf %>% 
    #filter(Nickname == GANTI ISINYA DI SHINY nya) %>% 
    filter(Nickname == "BoyceWP") %>% 
    head(15, tf_idf) %>% 
    ggplot(aes(x = reorder(word, tf_idf), y = tf_idf)) +
    geom_col() +
    coord_flip() +
    labs(
      x = "",
      y = "tf-idf",
      title = "Kata terpenting",
      subtitle = ""
    ) +
    theme_light()
```

```{r}
  restaurant_data_dtm <- restaurant_dataPerKata %>%
    count(Nickname, word) %>%
    cast_dtm(Nickname, word, n)

  restaurant_data_dtm

  restaurant_data_lda <- LDA(restaurant_data_dtm, k = 5)
  restaurant_data_lda
  
  restaurant_data_beta <- restaurant_data_lda %>% 
    tidy(matrix = "beta") %>% 
    rename(word = term) %>% 
    arrange(topic, desc(beta))
  
  restaurant_data_beta
  
  restaurant_data_beta %>% 
    group_by(topic) %>% 
    head(10, beta)  
  
  restaurant_data_beta %>%
    #filter(topic == SESUAIKAN DENGAN SHINY) %>%
    filter(topic == 1) %>%
    head(10, beta) %>%
    ggplot(aes(x = reorder(word, beta), y = beta)) + 
    geom_col() +
    coord_flip() +  
    labs(
      x = "",
      y = expression(beta),
      title = "Kata kunci pada topik 1"
    ) +
    theme_light()
```

Sentimen
```{r}
  review = as.character(restaurant_data$Review)

  get_nrc_sentiment('happy')
  get_nrc_sentiment('excitement')

  s = get_nrc_sentiment(review)
  
  review_sentiment = cbind(restaurant_data$Review,s)

  hasil_sentiment = barplot(colSums(s), col = rainbow(10), ylab = 'count', main = 'Sentiment Score')
  
```



```{r UI}
  ui = dashboardPage(
    dashboardHeader(
      color = "violet" ,title = "My Dashboard" , inverted = TRUE
    ),
    dashboardSidebar(
      size = "thin", color = "violet", inverted = TRUE , 
      sidebarMenu(
        menuItem("Iris", tabName = "iris", icon = icon("tree")),
        menuItem("Data Restaurant", tabName = "restaurant", icon = icon("chart"))
      )
    ),
    dashboardBody(
      tabItems(
        tabItem("iris",
            box(plotOutput("correlation_plot"), width = 12),
            box(
              selectInput(inputId = "features" , 
                          label = "Features :" ,
                          c("Sepal.Width", "Petal.Length",
                            "Petal.Width")), width = 4)    
        ),
        
        tabItem("restaurant",
                fluidPage(
                  h1("Data restaurant")),
                  dataTableOutput("restaurant")
        )
      )
    )
  )
```

```{r Server}
  server = function(input,output,session){
    output$correlation_plot = renderPlot(
      plot(iris$Sepal.Length, iris[[input$features]], xlab = "sepal Length", ylab = "Features")
    )
    
    output$restaurant = renderDataTable(restaurant_data)
  }
  
  
```

```{r}
  shinyApp(ui = ui,server = server)
```