---
title: "TugasAkhir"
author: "Khalil"
date: "1/16/2021"
output: pdf_document
---

```{r}
  #shiny
  library(shiny)
  library(ggplot2)
  library(plotly)
  library(shinydashboard)
  library(DT)
  # library(semantic.dashboard)
  
  #Algoritma LDA
  library(tidytext)
  library(dplyr)
  library(topicmodels)
  library(tm)

  #sentimen
  library(syuzhet)
  library(e1071)
  library(caret)

  #library(skimr)

  #lokasi projek
  library(here)
  library(vroom)

```

Scrapping Data
```{r}
  library(rvest)
  library(xml2)
  
```

```{r}
  laman_web <- "https://www.tripadvisor.com/Restaurant_Review-g60763-d4737024-Reviews-5_Napkin_Burger_Hell_s_Kitchen-New_York_City_New_York.html" #input alamat link
  restaurant = read_html(laman_web) #membaca html di R
```


```{r}
  nickname <- html_nodes(restaurant, ".member_info .info_text") #memasukkan element 
  nickname_data_lama <- html_text(nickname) #menghilangkan kata <span> dll.
  nickname_tabel = c(nickname_data_lama) #memasukkan ke array
  
  # total_review <- html_nodes(restaurant, ".reviewerBadge") #memasukkan element 
  # total_review_data_lama <- html_text(total_review) #menghilangkan kata <span> dll.
  # total_review_tabel = c(total_review_data_lama) #memasukkan ke array
  
  visit <- html_nodes(restaurant, ".prw_reviews_stay_date_hsx") #memasukkan element 
  visit_data_lama <- html_text(visit) #menghilangkan kata <span> dll.
  visit_data_lama = gsub("Date of visit: ","",visit_data_lama)
  visit_tabel = c(visit_data_lama) #memasukkan ke array
  
  title <- html_nodes(restaurant, ".noQuotes") #memasukkan element 
  title_data_lama <- html_text(title) #menghilangkan kata <span> dll.
  title_tabel = c(title_data_lama) #memasukkan ke array
  
  review <- html_nodes(restaurant, ".partial_entry") #memasukkan element 
  review_data_lama <- html_text(review) #menghilangkan kata <span> dll.
  review_tabel = c(review_data_lama) #memasukkan ke array
  
  for(i in seq(10,990,10)){
    laman_web_baru = paste("https://www.tripadvisor.com/Restaurant_Review-g60763-d4737024-Reviews-or",i,sep = "")
    laman_web_baru = paste(laman_web_baru, "-5_Napkin_Burger_Hell_s_Kitchen-New_York_City_New_York.html",sep="")
    restaurant_baru = read_html(laman_web_baru)
    
    nickname_baru <- html_nodes(restaurant_baru, ".member_info .info_text") #memasukkan element 
    nickname_data_baru <- html_text(nickname_baru) #menghilangkan kata <span> dll.
    nickname_tabel = c(nickname_tabel,nickname_data_baru) #memasukkan ke array
    
    # total_review <- html_nodes(restaurant, ".reviewerBadge") #memasukkan element 
    # total_review_data_lama <- html_text(total_review) #menghilangkan kata <span> dll.
    # total_review_tabel = c(total_review_data_lama) #memasukkan ke array
    
    visit_baru <- html_nodes(restaurant_baru, ".prw_reviews_stay_date_hsx") #memasukkan element 
    visit_data_baru <- html_text(visit_baru) #menghilangkan kata <span> dll.
    visit_data_baru = gsub("Date of visit: ","",visit_data_baru)
    visit_tabel = c(visit_tabel,visit_data_baru) #memasukkan ke array
    
    title_baru <- html_nodes(restaurant_baru, ".noQuotes") #memasukkan element 
    title_data_baru <- html_text(title_baru) #menghilangkan kata <span> dll.
    title_tabel = c(title_tabel,title_data_baru) #memasukkan ke array
    
    review_baru <- html_nodes(restaurant_baru, ".partial_entry") #memasukkan element 
    review_data_baru <- html_text(review_baru) #menghilangkan kata <span> dll.
    review_tabel = c(review_tabel,review_data_baru) #memasukkan ke array
  }
  
  restaurant_data = data.frame(nickname = nickname_tabel,Visit = visit_tabel,Title = title_tabel ,Review = review_tabel)


```

```{r}
  write.csv(restaurant_data, file.choose())
```


Word Cloud
```{r}
  library(wordcloud)
  library(RColorBrewer)
  library(wordcloud2)

  restaurant_data = vroom(here("Tugas AKhir", "Tugas Akhir Data Science", "dataset", "review2.csv"))
  restaurant_data %>% select(-Families) -> restaurant_data

  text <- restaurant_data$Review
  docs <- Corpus(VectorSource(text))

  docs <- docs %>%
  tm_map(removeNumbers) %>%
  tm_map(removePunctuation) %>%
  tm_map(stripWhitespace)
  docs <- tm_map(docs, content_transformer(tolower))
  docs <- tm_map(docs, removeWords, stopwords("english"))
  
  dtm <- TermDocumentMatrix(docs) 
  matrix <- as.matrix(dtm) 
  words <- sort(rowSums(matrix),decreasing=TRUE) 
  df <- data.frame(word = names(words),freq=words)
  
  set.seed(1234) 
  wordcloud(words = df$word, freq = df$freq, min.freq = 1, 
            scale=c(3.5,0.25),
            max.words=200, random.order=FALSE, rot.per=0.35,    
            colors=brewer.pal(8, "Dark2"))
```

Kata yang paling sering muncul berdasarkan nickname
```{r}
  restaurant_data %>% 
  unnest_tokens(word, Review) %>%
  ungroup() %>%
  anti_join(stop_words) -> restaurant_dataPerKata 

  restaurant_dataPerKata %>% 
    count(Nickname, word, sort = TRUE)
  
  restaurant_data_ifidf <- restaurant_dataPerKata %>% 
    count(Nickname, word, sort = TRUE) %>% 
    bind_tf_idf(word, Nickname, n)
  
  #Kata Penting pada tiap-tiap orang
  restaurant_data_ifidf %>% 
    filter(Nickname == "richardnW9222JN") %>% 
    head(15, tf_idf) %>% 
    ggplot(aes(x = reorder(word, tf_idf), y = tf_idf)) +
    geom_col() +
    coord_flip() +
    labs(
      x = "",
      y = "tf-idf",
      title = "Kata terpenting",
      subtitle = ""
    ) +
    theme_light()
```

Kata yang paling sering muncul berdasarkan topik (LDA)
```{r}
  restaurant_data_dtm <- restaurant_dataPerKata %>%
    count(Traveler_type, word) %>%
    cast_dtm(Traveler_type, word, n)

  restaurant_data_dtm

  restaurant_data_lda <- LDA(restaurant_data_dtm, k = 5)
  restaurant_data_lda
  
  restaurant_data_beta <- restaurant_data_lda %>% 
    tidy(matrix = "beta") %>% 
    rename(word = term) %>% 
    arrange(topic, desc(beta))
  
  restaurant_data_beta
  
  restaurant_data_beta %>% 
    group_by(topic) %>% 
    head(10, beta)  
  
  restaurant_data_beta %>%
    filter(topic == 2) %>%
    head(10, beta) %>%
    ggplot(aes(x = reorder(word, beta), y = beta)) + 
    geom_col() +
    coord_flip() +  
    labs(
      x = "",
      y = expression(beta),
      title = "Kata kunci pada topik 2"
    ) +
    theme_light()
```

Sentimen
```{r}
  review = as.character(restaurant_data_beta$word)

  s = get_nrc_sentiment(review)
  
  review_sentiment = cbind(restaurant_data_beta$word,s)

  hasil_sentiment = barplot(colSums(s), col = rainbow(10), ylab = 'count', main = 'Sentiment Score')
  
```

```{r}
  opsi_nickname = unique(restaurant_data$Nickname)
  opsi_topic = unique(restaurant_data_beta$topic)
```


```{r UI}
  ui = dashboardPage(
    
    skin = "green",
    dashboardHeader(
      title = "My Dashboard" 
    ),
    
    dashboardSidebar(
      sidebarMenu(
        menuItem("Analisa", tabName = "analisa", icon = icon("line-chart"),
                   menuSubItem('nickname', tabName = 'kelompok_nickname'),
                   menuSubItem('Topik', tabName = 'kelompok_topik')
                 ),
        menuItem("Word Cloud", tabName = "word_cloud",icon = icon("cloud")),
        menuItem("Sentimen", tabName = "sentimen", icon = icon("wordpress")),
        menuItem("Data Restaurant", tabName = "restaurant", icon = icon("calendar"))
      )
    ),
    
    dashboardBody(
      tabItems(
        
        tabItem(tabName = 'kelompok_nickname',
                h2("Kata yang Paling Sering Digunakan Berdasarkan nickname"),
                    box (selectInput(inputId = "nickname",
                                  label =  "nickname : ",
                                  choices = opsi_nickname,
                                  selected = opsi_nickname[[1]]),
                         numericInput("nickname_angka", "Angka :", 10,
                                  min = 1, max = 100), 
                         width = 4),
                    box (plotlyOutput(outputId = "opsi_nickname_plot"),  width = 8)

        ),
        
        tabItem(tabName = 'kelompok_topik',
                h2("Kata yang Paling Sering Digunakan Berdasarkan Topik"),
                    box (selectInput(inputId = "topic",
                                  label =  "Topic",
                                  choices = opsi_topic,
                                  selected = opsi_topic[[1]]),
                         numericInput("topic_angka", "Angka :", 10,
                                  min = 1, max = 100), 
                         width = 4),
                    box (plotlyOutput(outputId = "opsi_topic_plot"),  width = 8)

        ),
        
        tabItem(tabName = 'kelompok_topik',
                h2("Pengelompokan berdasarkan nickname :"),
                box(plotOutput("kelompok_topik"),width = 8)
        ),
        
        tabItem("word_cloud",
              plotOutput("word_cloud")
        ),
        
        tabItem("sentimen",
              box(plotOutput("sentimen_plot"),width = 12)
        ),
        
        tabItem("restaurant",
                fluidPage(
                  h1("Data restaurant")),
                  dataTableOutput("restaurant")
        )
      )
    )
  )
```


```{r Server}
  server = function(input,output){
    
    opsi_nickname_plot <- reactive({
      
      restaurant_data_ifidf %>% 
            filter(Nickname %in% input$nickname ) %>% 
            head(input$nickname_angka, tf_idf) %>% 
            ggplot(aes(x = reorder(word, tf_idf), y = tf_idf, fill = factor(reorder(word, tf_idf)))) +
            geom_col() +
            coord_flip() +
            labs(
              x = "",
              y = "tf-idf",
              title = "Kata terpenting",
              subtitle = "",
              fill = "Kata"
            ) +
            theme_light()
      
    })
    output$opsi_nickname_plot = renderPlotly({
          ggplotly(opsi_nickname_plot())
    })
    
    opsi_topic_plot <- reactive({
      
      restaurant_data_beta %>% 
            filter(topic %in% input$topic ) %>% 
            head(input$topic_angka, beta) %>% 
            ggplot(aes(x = reorder(word, beta), y = beta, fill = factor(reorder(word, beta)))) +
            geom_col() +
            coord_flip() +
            labs(
              x = "",
              y = "Betta",
              title = "Kata terpenting",
              subtitle = "",
              flil = "Kata"
            ) +
            theme_light()
      
      
    })
    output$opsi_topic_plot = renderPlotly({
          ggplotly(opsi_topic_plot())
    })
    
    output$word_cloud = renderPlot(
        wordcloud(words = df$word, freq = df$freq, min.freq = 1, 
            max.words=200, random.order=FALSE, rot.per=0.35,  
            scale=c(3.75,0.3),
            colors=brewer.pal(8, "Dark2"))
    )
      
    output$sentimen_plot = renderPlot(
        barplot(colSums(s), col = rainbow(10), ylab = 'count', main = 'Sentiment Score')
    )
    
    output$restaurant = renderDataTable(restaurant_data)
  }
  
  
```

```{r}
  shinyApp(ui = ui,server = server)
```