---
title: "Murders"
author: "Khalil"
date: "11/5/2020"
output:
  pdf_document: default
  word_document: default
---

1.)
```{r}
  library(dslabs)
  data(murders)
  
  pop= murders$population
  sort(pop)[1]
```

2.) 
```{r}
  index = order(murders$population)
  index[1]
```

3.) 
```{r}
  x = which.min(pop)
```

4.) 
```{r}
  populasi_terkecil = (murders$state[index])[1]
  populasi_terkecil
```

5.) 
```{r}
  ranks = rank(pop)
  my_df = data.frame(nama = murders$state , peringkat = ranks)
  my_df

```

6.) 
```{r}
  ind = order(my_df$peringkat)
  my_dff = data.frame(nama = (sort(murders$state))[ind], populasi = sort(murders$population), peringkat = sort(ranks))
  my_dff
```

7.) 
```{r}
  population_in_millions <- log10(murders$population)
  total_gun_murders <- murders$total
  plot(population_in_millions, total_gun_murders) 
```

8.) 
```{r}
  population = murders$population /1000000
  hist(population)
```

9.)
```{r}
  populasi_negara=murders$population/10^5
  plot(populasi_negara~region,data=murders)
```

